version: '3.1'

services:
      postgres:
          image: postgres
          restart: always
          environment:
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: 1q2w3e4r
               POSTGRES_DB: postgres
          ports:
              - "5432:5432"
      pgadmin:
          image: dpage/pgadmin4
          restart: always
          environment:
              PGADMIN_DEFAULT_EMAIL: berkaybayrak296@gmail.com
              PGADMIN_DEFAULT_PASSWORD: 1q2w3e4r
          ports:
             - "5050:80"